config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'application#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/tv_shows/most_reviewed', to: "tv_shows#reviewed"
  get '/tv_shows/currently_airing', to: "tv_shows#currently_airing"

  resources :users, only: [:edit, :show, :update]
  resources :actors
  resources :characters
  resources :reviews, except: [:index, :show, :new]
  resources :tv_shows do
    resources :actors, only: [:index]
    resources :characters, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  
end

app/models/actor.rb
class Actor < ApplicationRecord
    has_many :characters, :dependent => :destroy
    has_many :tv_shows, through: :characters
    belongs_to :creator, class_name: "User" 
    belongs_to :editor, class_name: "User"

    validates :name, :age, presence: :true
    validates :name, uniqueness: true

    def self.alphabetical
        self.order(name: :asc)
    end
    
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    before_action :set_actor, except: [:index, :new, :create]
    before_action :creator_match, only: [:destroy]

    def index
        if params[:tv_show_id] && @show =  TvShow.find_by_id(params[:tv_show_id])
            @actors = @show.actors.alphabetical
        else
            @actors = Actor.all
        end
    end

    def new
        @actor = Actor.new
    end

    def create
        @actor = current_user.created_actors.build(actor_params)
        @actor.editor = current_user

        if @actor.save
            creation_success("Actor")
            redirect_to actor_path(@actor)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        @actor.editor = current_user

        if @actor.update(actor_params)
            update_success("Actor")
            redirect_to actor_path(@actor)
        else
            render :edit
        end
    end

    def destroy
            @actor.destroy
            deletion_success("Actor")
            redirect_to actors_path
    end
    
    private

    def actor_params
        params.require(:actor).permit(:name, :age)
    end

    def set_actor
        @actor = Actor.find(params[:id])
    end   
    
    def creator_match
        if @actor.creator != current_user
            redirect_to actor_path(@actor)
        end
    end

end

app/helpers/actors_helper.rb
module ActorsHelper

    def display_header_actors(show)
        if show
            tag.h1("#{show.name}'s Actors")
        else
            tag.h1("Actors")
        end
    end

    def display_add_actor(show)
        if !show
            link_to "Create a new actor here", new_actor_path  
        end
    end

    def display_delete_actor(actor)
        if actor.creator == current_user
            button_to "Delete Actor", actor_path(@actor), :method => :delete
        end
    end

end

app/views/actors/_form.html.erb
<%= render partial: "application/errors", locals: {model: @actor} %>
<%= form_for(@actor) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :age %>
    <%= f.text_field :age %><br>

    <%= f.submit %>
<% end %>

app/views/actors/edit.html.erb
<h1>Edit Actor</h1>
<hr>
<%= render 'form' %>

app/views/actors/index.html.erb
<%= display_header_actors(@show) %>
<hr>
<ul><% @actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %></li>
<% end %></ul><br>

<%= display_add_actor(@show) %>

app/views/actors/new.html.erb
<h1>Create a New Actor</h1>
<hr>
<%= render 'form' %>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>
Created by: <%= @actor.creator.name %> on <%= @actor.date_readable(@actor.created_at) %> || Last edited by: <%= @actor.editor.name %> on <%= @actor.date_readable(@actor.updated_at) %>
<hr>
<h2><%= @actor.age %> years old</h2><br>

<h3>Roles:</h3>

<% if @actor.characters.length > 0 %>
    <ul><% @actor.characters.each do |character| %>
        <li><%= link_to character.name, character_path(character) %> on <%= link_to character.tv_show.name, tv_show_path(character.tv_show) %></li>
    <% end %></ul>
<% else %>
    This actor currently does not have any roles created. You may <%= link_to "add one", new_character_path %> if you'd like.
<% end %><br><br><br>

<%= link_to "Edit Actor", edit_actor_path(@actor) %><br><br>

<%= display_delete_actor(@actor) %>