config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'application#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/tv_shows/most_reviewed', to: "tv_shows#reviewed"
  get '/tv_shows/currently_airing', to: "tv_shows#currently_airing"

  resources :users, only: [:edit, :show, :update]
  resources :actors
  resources :characters
  resources :reviews, except: [:index, :show, :new]
  resources :tv_shows do
    resources :actors, only: [:index]
    resources :characters, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    has_many :reviews, :dependent => :destroy
    has_many :characters, :dependent => :destroy
    has_many :actors, through: :characters
    belongs_to :creator, class_name: "User" 
    belongs_to :editor, class_name: "User"

    validates :name, :synopsis, :start_date, presence: :true
    validates :name, uniqueness: :true
    
    def dateform(date)
        date.strftime("%Y-%m-%d")
    end

    def self.by_review
        self.order(reviews: :asc)
    end

    def self.currently_airing
        where(currently_airing: true)
    end

end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
    before_action :set_show, except: [:index, :new, :create, :reviewed, :currently_airing]
    before_action :creator_match, only: [:destroy]
    
    def index
        @shows = TvShow.all
    end

    def new
        @show = TvShow.new
    end

    def create
        @show = current_user.created_tv_shows.build(show_params)
        @show.editor = current_user

        if @show.save
            flash[:message] = "TV Show was successfully created."
            redirect_to tv_show_path(@show)
        else
            render :new
        end
    end

    def reviewed
        @show = TvShow.by_review.first
    end

    def show
    end

    def currently_airing
        @shows = TvShow.currently_airing
    end

    def edit
    end

    def update
        @show.editor = current_user
        if @show.update(show_params)
            flash[:message] = "TV Show was successfully updated."
            redirect_to tv_show_path(@show)
        else
            render :edit
        end
    end

    def destroy
        @show.destroy
        redirect_to tv_shows_path
    end
    
    private

    def show_params
        params.require(:tv_show).permit(:name, :start_date, :end_date, :currently_airing, :synopsis, :network)
    end

    def set_show
        @show = TvShow.find(params[:id])
    end

    def creator_match
        if @show.creator != current_user
            redirect_to tv_show_path(@show)
        end
    end

    
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper

    def currently_airing?
        if @show.currently_airing
            "Currently airing"
        else
            "Not currently airing"
        end
    end

    def has_characters
        @show.characters.length > 0
    end

    def display_edit_review(review)
        if current_user == review.user 
            link_to "(edit review)", edit_review_path(review)
        end
    end

    def display_delete_show(show)
        if show.creator == current_user
            button_to "Delete show", tv_show_path(show), :method => :delete
        end
    end

    def display_add_character(show)
        if !show
            link_to "Create a new character here", new_character_path  
        end
    end

    def populated_end_date(show, f)
        if show.end_date
            f.text_field :end_date, value: show.dateform(show.end_date)
        else
            f.text_field :end_date
        end
    end

end

app/views/tv_shows/_display.html.erb
<h1><%= @show.name %></h1>
Created by: <%= @show.creator.name %> on <%= @show.date_readable(@show.created_at) %> || Last Edited by: <%= @show.editor.name %> on <%= @show.date_readable(@show.updated_at) %>
<hr>
<strong><%= @show.network %> Network | <%= currently_airing? %></strong><br><br>

<strong>Start Date:</strong> <%= @show.date_readable(@show.start_date) %><br>
<% if !@show.currently_airing %>
    <strong>End Date:</strong> <%= @show.date_readable(@show.end_date) %><br>
<% end %>
<h3>Synopsis:</h3>
<p><%= @show.synopsis %></p>

<h4><%= link_to "See #{@show.name}'s  actors", tv_show_actors_path(@show) %></h4>
<h4><%= link_to "See #{@show.name}'s characters", tv_show_characters_path(@show) %></h4>
<h4><%= link_to "Create a new character for #{@show.name}", new_tv_show_character_path(@show) %></h4>

<h3>Reviews:</h3>
<ul><% @show.reviews.each do |review| %>
    <li><%= review.body %> - <%= review.user.name %> <%= display_edit_review(review) %></li><br>
<% end %></ul>

<h4><%= link_to "Leave a Review", new_tv_show_review_path(@show) %></h4>

<%= link_to "Edit Show", edit_tv_show_path(@show) %><br><br>

<%= display_delete_show(@show) %>

app/views/tv_shows/currently_airing.html.erb
<h1>Currently Airing Shows</h1>
<ul><% @shows.each do |show| %>
    <li><%= link_to show.name, tv_show_path(show) %></li>
<% end %></ul>

app/views/tv_shows/edit.html.erb
<h1>Edit <%= @show.name %> </h1>
<hr>
<%= render partial: "application/errors", locals: {model: @show} %>
<h5>Please format start and end dates as such: YYYY-MM-DD</h5>
<%= form_for(@show) do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %><br>
    
    <%= f.label :start_date, "Start Date: " %>
    <%= f.text_field :start_date, value: @show.dateform(@show.start_date) %><br>

    <%= f.label :currently_airing, "Currently Airing? " %>
    <%= f.check_box :currently_airing %><br>
    
    <%= f.label :end_date, "End Date (if not currently airing): " %>
    <%= populated_end_date(@show, f)%><br>

    <%= f.label :network, "Network: " %>
    <%= f.text_field :network %><br>

    <%= f.label :synopsis, "Synopsis: " %><br>
    <%= f.text_area :synopsis %><br>

    <%= f.submit %>
<% end %>

app/views/tv_shows/index.html.erb
<h1>TV Shows</h1>
<%= link_to "view show with the most reviews", tv_shows_most_reviewed_path %>
<hr>
<ul><% @shows.each do |show| %>
    <li><%= link_to show.name, tv_show_path(show) %></li>
<% end %></ul><br>

<%= link_to "Create a new show here", new_tv_show_path %>

app/views/tv_shows/new.html.erb
<h1>Create TV Show</h1>
<hr>
<%= render partial: "application/errors", locals: {model: @show} %>
<h5>Please format start and end dates as such: YYYY-MM-DD</h5>
<%= form_for(@show) do |f| %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %><br>
    
    <%= f.label :start_date, "Start Date: " %>
    <%= f.text_field :start_date %><br>

    <%= f.label :currently_airing, "Currently Airing? " %>
    <%= f.check_box :currently_airing %><br>
    
    <%= f.label :end_date, "End Date (if not currently airing): " %>
    <%= f.text_field :end_date %><br>

    <%= f.label :network, "Network: " %>
    <%= f.text_field :network %><br>

    <%= f.label :synopsis, "Synopsis: " %><br>
    <%= f.text_area :synopsis %><br>

    <%= f.submit %>
<% end %>

app/views/tv_shows/reviewed.html.erb
<%= render 'display' %>

app/views/tv_shows/show.html.erb
<%= render 'display' %>