config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'application#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/tv_shows/most_reviewed', to: "tv_shows#reviewed"
  get '/tv_shows/currently_airing', to: "tv_shows#currently_airing"

  resources :users, only: [:edit, :show, :update]
  resources :actors
  resources :characters
  resources :reviews, except: [:index, :show, :new]
  resources :tv_shows do
    resources :actors, only: [:index]
    resources :characters, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_actors, foreign_key: "creator_id", class_name: "Actor"
  has_many :edited_actors, foreign_key: "editor_id", class_name: "Actor"
  has_many :created_tv_shows, foreign_key: "creator_id", class_name: "TvShow"
  has_many :edited_tv_shows, foreign_key: "editor_id", class_name: "TvShow"
  has_many :created_characters, foreign_key: "creator_id", class_name: "Character"
  has_many :edited_characters, foreign_key: "editor_id", class_name: "Character"
  has_many :reviews
  has_secure_password

  validates :name, :email, presence: :true
  validates :email, uniqueness: :true

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex(10)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, except: [:new, :create]
    before_action :current_user_match, except: [:new, :create]
    skip_before_action :restrict_access, only: [:new, :create]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            creation_success(@user)
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:message] = "User was successfully updated."
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
    
    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def current_user_match
        if @user != current_user
            flash[:notice] = "That's not yours!"
            redirect_to user_path(current_user)
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %>'s Information</h1>
<hr>
<%= render partial: "application/errors", locals: {model: @user} %>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :email %>
    <%= f.text_field :email %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<hr>
<%= render partial: "application/errors", locals: {model: @user} %>
<%= form_for :user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :email %>
    <%= f.text_field :email %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Homepage</h1>
<%= link_to "Create a TV Show", new_tv_show_path %> |
<%= link_to "Create an Actor", new_actor_path %> |
<%= link_to "Create a Character", new_character_path %>
<hr>
<h2>Shows Created (<%= @user.created_tv_shows.length %>)</h2>
<% @user.created_tv_shows.each do |show| %>
    <p><%= link_to show.name, tv_show_path(show) %></p>
<% end %><br>

<h2>Actors Created (<%= @user.created_actors.length %>)</h2>
<% @user.created_actors.each do |actor| %>
    <p><%= link_to actor.name, actor_path(actor) %></p>
<% end %><br>

<h2>Characters Created (<%= @user.created_characters.length %>)</h2>
<% @user.created_characters.each do |character| %>
    <p><%= link_to character.name, character_path(character) %></p>
<% end %><br>

<%= link_to "Edit Information", edit_user_path(@user) %>