config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'application#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/tv_shows/most_reviewed', to: "tv_shows#reviewed"
  get '/tv_shows/currently_airing', to: "tv_shows#currently_airing"

  resources :users, only: [:edit, :show, :update]
  resources :actors
  resources :characters
  resources :reviews, except: [:index, :show, :new]
  resources :tv_shows do
    resources :actors, only: [:index]
    resources :characters, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to "Home", user_path(current_user) %> |
      <%= link_to "TV Shows", tv_shows_path %> |
      <%= link_to "Actors", actors_path %> |
      <%= link_to "Characters", characters_path %>
    <% else %>
      <%= link_to "Home", root_path %>
    <% end %><br><br>

    <% if flash[:notice] %>
      <div class="field_with_errors"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:message] %>
      <div class="flash_message"><%= flash[:message] %></div>
    <% end %>

    <%= yield %>

    <% if logged_in? %>
      <hr>
      <%= button_to "Log Out", logout_path, :method => :delete %>
    <% end %>
    
  </body>
</html>